# You need the AZURE_WEB_APP_NAME and to download the deployment profile and
# add it as a secret to this repo with the name AZURE_WEBAPP_PUBLISH_PROFILE
name: Trigger auto deployment for demo-container

env:
  # !!!! UPDATE THESE VARIABLE BELOW !!!!
  DOCKERHUB_USERNAME: billyae
  DOCKERHUB_PASSWORD: Yzh5480745

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo. Remove comments to enable
  #push:
  #  branches:
  #    [ main ]

  # Allow mannually trigger
  workflow_dispatch:

jobs:
    build:
      name: push docker image to docker hub
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: login to docker hub
          id: docker-hub
          env:
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_PASSWORD}}
          run: |
            docker login -u $username -p $password 
        - name: build the docker image
          id: build-docker-image
          run: |
            ls -la 
            docker build . -f Dockerfile -t billyae/bootcamp_week4:lastest
        - name: push the docker image
          id: push-docker-image
          run: docker push ${{secrets.DOCKERHUB_USERNAME}}/bootcamp_week4:latest
